const player = document.getElementById('player');
const sin = document.getElementById('sin');
const scoreDisplay = document.getElementById('score');
let playerPosition = window.innerWidth / 2 - 25;
let score = 0;
let gameOver = false;

document.addEventListener('keydown', (event) => {
    if (event.key === 'ArrowLeft' && playerPosition > 0) {
        playerPosition -= 15;
    } else if (event.key === 'ArrowRight' && playerPosition < window.innerWidth - 50) {
        playerPosition += 15;
    }
    player.style.left = playerPosition + 'px';
});

function dropSin() {
    let sinPosition = Math.floor(Math.random() * (window.innerWidth - 50));
    sin.style.left = sinPosition + 'px';
    let sinHeight = 0;
    
    const sinInterval = setInterval(() => {
        if (gameOver) {
            clearInterval(sinInterval);
            return;
        }

        sinHeight += 5;
        sin.style.top = sinHeight + 'px';

        if (sinHeight > window.innerHeight - 70) {
            clearInterval(sinInterval);
            score++;
            scoreDisplay.innerText = `Score: ${score}`;
            dropSin(); // Drop a new sin
        }

        // Collision detection
        if (sinHeight > window.innerHeight - 70 && sinPosition > playerPosition - 50 && sinPosition < playerPosition + 50) {
            gameOver = true;
            alert(`Game Over! Your score was: ${score}`);
        }
    }, 100);
}

dropSin();
body {
    margin: 0;
    background: lightblue;
    overflow: hidden;
}

.game-container {
    position: relative;
    width: 100vw;
    height: 100vh;
    background: url('https://example.com/clouds.png') repeat;
    background-size: cover;
}

.player {
    position: absolute;
    bottom: 20px;
    left: 50%;
    width: 50px;
    height: 50px;
    background: yellow; /* Player color */
    border-radius: 50%;
    transform: translateX(-50%);
}

.sin {
    position: absolute;
    top: 0;
    width: 50px;
    height: 50px;
    background: red; /* Sin color */
}

.score {
    position: absolute;
    top: 20px;
    left: 20px;
    font-size: 24px;
    color: black;
}

